### ISSUE TITLE
[Suggestion] Maybe eliminate this with enumerate?

### ISSUE THREAD

**Issue by ShahriyarR** [akhundMurad/supporting-crud-python-example#1]
Instead of doing manual row increment, maybe it is better to get it from enumerate?

https://github.com/akhundMurad/supporting-crud-python-example/blob/a694ec13025874313c50779862465f710ffdadff/src/business_logic/services/attendance_report_load_service.py#L60

**Comment by akhundMurad** [comment]
Good suggestion, looks like enumerate will suit better.

**Comment by akhundMurad** [comment]
And also I think we should test this logic more thoroughly
